// Taken from https://gist.github.com/NoelDavies/a7e8e3d959a0619362b291bb10a8fd8d
export const swordShieldPokemon = [
    { id: 1, identifier: 'Bulbasaur' },
    { id: 2, identifier: 'Ivysaur' },
    { id: 3, identifier: 'Venusaur' },
    { id: 4, identifier: 'Charmander' },
    { id: 5, identifier: 'Charmeleon' },
    { id: 6, identifier: 'Charizard' },
    { id: 7, identifier: 'Squirtle' },
    { id: 8, identifier: 'Wartortle' },
    { id: 9, identifier: 'Blastoise' },
    { id: 10, identifier: 'Caterpie' },
    { id: 11, identifier: 'Metapod' },
    { id: 12, identifier: 'Butterfree' },
    { id: 25, identifier: 'Pikachu' },
    { id: 893, identifier: 'Pikachu 1' },
    { id: 894, identifier: 'Pikachu 2' },
    { id: 895, identifier: 'Pikachu 3' },
    { id: 896, identifier: 'Pikachu 4' },
    { id: 897, identifier: 'Pikachu 5' },
    { id: 898, identifier: 'Pikachu 6' },
    { id: 899, identifier: 'Pikachu 7' },
    { id: 26, identifier: 'Raichu' },
    { id: 900, identifier: 'Raichu 1' },
    { id: 35, identifier: 'Clefairy' },
    { id: 36, identifier: 'Clefable' },
    { id: 37, identifier: 'Vulpix' },
    { id: 903, identifier: 'Vulpix 1' },
    { id: 38, identifier: 'Ninetales' },
    { id: 904, identifier: 'Ninetales 1' },
    { id: 43, identifier: 'Oddish' },
    { id: 44, identifier: 'Gloom' },
    { id: 45, identifier: 'Vileplume' },
    { id: 50, identifier: 'Diglett' },
    { id: 905, identifier: 'Diglett 1' },
    { id: 51, identifier: 'Dugtrio' },
    { id: 906, identifier: 'Dugtrio 1' },
    { id: 52, identifier: 'Meowth' },
    { id: 907, identifier: 'Meowth 1' },
    { id: 908, identifier: 'Meowth 2' },
    { id: 53, identifier: 'Persian' },
    { id: 909, identifier: 'Persian 1' },
    { id: 58, identifier: 'Growlithe' },
    { id: 59, identifier: 'Arcanine' },
    { id: 66, identifier: 'Machop' },
    { id: 67, identifier: 'Machoke' },
    { id: 68, identifier: 'Machamp' },
    { id: 77, identifier: 'Ponyta' },
    { id: 913, identifier: 'Ponyta 1' },
    { id: 78, identifier: 'Rapidash' },
    { id: 914, identifier: 'Rapidash 1' },
    { id: 83, identifier: 'Farfetch’d' },
    { id: 915, identifier: 'Farfetch’d 1' },
    { id: 90, identifier: 'Shellder' },
    { id: 91, identifier: 'Cloyster' },
    { id: 92, identifier: 'Gastly' },
    { id: 93, identifier: 'Haunter' },
    { id: 94, identifier: 'Gengar' },
    { id: 95, identifier: 'Onix' },
    { id: 98, identifier: 'Krabby' },
    { id: 99, identifier: 'Kingler' },
    { id: 106, identifier: 'Hitmonlee' },
    { id: 107, identifier: 'Hitmonchan' },
    { id: 109, identifier: 'Koffing' },
    { id: 110, identifier: 'Weezing' },
    { id: 920, identifier: 'Weezing 1' },
    { id: 111, identifier: 'Rhyhorn' },
    { id: 112, identifier: 'Rhydon' },
    { id: 118, identifier: 'Goldeen' },
    { id: 119, identifier: 'Seaking' },
    { id: 122, identifier: 'Mr. Mime' },
    { id: 921, identifier: 'Mr. Mime 1' },
    { id: 129, identifier: 'Magikarp' },
    { id: 130, identifier: 'Gyarados' },
    { id: 131, identifier: 'Lapras' },
    { id: 132, identifier: 'Ditto' },
    { id: 133, identifier: 'Eevee' },
    { id: 134, identifier: 'Vaporeon' },
    { id: 135, identifier: 'Jolteon' },
    { id: 136, identifier: 'Flareon' },
    { id: 143, identifier: 'Snorlax' },
    { id: 150, identifier: 'Mewtwo' },
    { id: 151, identifier: 'Mew' },
    { id: 163, identifier: 'Hoothoot' },
    { id: 164, identifier: 'Noctowl' },
    { id: 170, identifier: 'Chinchou' },
    { id: 171, identifier: 'Lanturn' },
    { id: 172, identifier: 'Pichu' },
    { id: 173, identifier: 'Cleffa' },
    { id: 175, identifier: 'Togepi' },
    { id: 176, identifier: 'Togetic' },
    { id: 177, identifier: 'Natu' },
    { id: 178, identifier: 'Xatu' },
    { id: 182, identifier: 'Bellossom' },
    { id: 185, identifier: 'Sudowoodo' },
    { id: 194, identifier: 'Wooper' },
    { id: 195, identifier: 'Quagsire' },
    { id: 196, identifier: 'Espeon' },
    { id: 197, identifier: 'Umbreon' },
    { id: 202, identifier: 'Wobbuffet' },
    { id: 208, identifier: 'Steelix' },
    { id: 211, identifier: 'Qwilfish' },
    { id: 213, identifier: 'Shuckle' },
    { id: 215, identifier: 'Sneasel' },
    { id: 220, identifier: 'Swinub' },
    { id: 221, identifier: 'Piloswine' },
    { id: 222, identifier: 'Corsola' },
    { id: 949, identifier: 'Corsola 1' },
    { id: 223, identifier: 'Remoraid' },
    { id: 224, identifier: 'Octillery' },
    { id: 225, identifier: 'Delibird' },
    { id: 226, identifier: 'Mantine' },
    { id: 236, identifier: 'Tyrogue' },
    { id: 237, identifier: 'Hitmontop' },
    { id: 246, identifier: 'Larvitar' },
    { id: 247, identifier: 'Pupitar' },
    { id: 248, identifier: 'Tyranitar' },
    { id: 251, identifier: 'Celebi' },
    { id: 263, identifier: 'Zigzagoon' },
    { id: 950, identifier: 'Zigzagoon 1' },
    { id: 264, identifier: 'Linoone' },
    { id: 951, identifier: 'Linoone 1' },
    { id: 270, identifier: 'Lotad' },
    { id: 271, identifier: 'Lombre' },
    { id: 272, identifier: 'Ludicolo' },
    { id: 273, identifier: 'Seedot' },
    { id: 274, identifier: 'Nuzleaf' },
    { id: 275, identifier: 'Shiftry' },
    { id: 278, identifier: 'Wingull' },
    { id: 279, identifier: 'Pelipper' },
    { id: 280, identifier: 'Ralts' },
    { id: 281, identifier: 'Kirlia' },
    { id: 282, identifier: 'Gardevoir' },
    { id: 290, identifier: 'Nincada' },
    { id: 291, identifier: 'Ninjask' },
    { id: 292, identifier: 'Shedinja' },
    { id: 302, identifier: 'Sableye' },
    { id: 303, identifier: 'Mawile' },
    { id: 309, identifier: 'Electrike' },
    { id: 310, identifier: 'Manectric' },
    { id: 315, identifier: 'Roselia' },
    { id: 320, identifier: 'Wailmer' },
    { id: 321, identifier: 'Wailord' },
    { id: 324, identifier: 'Torkoal' },
    { id: 328, identifier: 'Trapinch' },
    { id: 329, identifier: 'Vibrava' },
    { id: 330, identifier: 'Flygon' },
    { id: 337, identifier: 'Lunatone' },
    { id: 338, identifier: 'Solrock' },
    { id: 339, identifier: 'Barboach' },
    { id: 340, identifier: 'Whiscash' },
    { id: 341, identifier: 'Corphish' },
    { id: 342, identifier: 'Crawdaunt' },
    { id: 343, identifier: 'Baltoy' },
    { id: 344, identifier: 'Claydol' },
    { id: 349, identifier: 'Feebas' },
    { id: 350, identifier: 'Milotic' },
    { id: 355, identifier: 'Duskull' },
    { id: 356, identifier: 'Dusclops' },
    { id: 360, identifier: 'Wynaut' },
    { id: 361, identifier: 'Snorunt' },
    { id: 362, identifier: 'Glalie' },
    { id: 385, identifier: 'Jirachi' },
    { id: 406, identifier: 'Budew' },
    { id: 407, identifier: 'Roserade' },
    { id: 415, identifier: 'Combee' },
    { id: 416, identifier: 'Vespiquen' },
    { id: 420, identifier: 'Cherubi' },
    { id: 421, identifier: 'Cherrim' },
    { id: 965, identifier: 'Cherrim 1' },
    { id: 422, identifier: 'Shellos' },
    { id: 966, identifier: 'Shellos 1' },
    { id: 423, identifier: 'Gastrodon' },
    { id: 967, identifier: 'Gastrodon 1' },
    { id: 425, identifier: 'Drifloon' },
    { id: 426, identifier: 'Drifblim' },
    { id: 434, identifier: 'Stunky' },
    { id: 435, identifier: 'Skuntank' },
    { id: 436, identifier: 'Bronzor' },
    { id: 437, identifier: 'Bronzong' },
    { id: 438, identifier: 'Bonsly' },
    { id: 439, identifier: 'Mime Jr.' },
    { id: 446, identifier: 'Munchlax' },
    { id: 447, identifier: 'Riolu' },
    { id: 448, identifier: 'Lucario' },
    { id: 449, identifier: 'Hippopotas' },
    { id: 450, identifier: 'Hippowdon' },
    { id: 451, identifier: 'Skorupi' },
    { id: 452, identifier: 'Drapion' },
    { id: 453, identifier: 'Croagunk' },
    { id: 454, identifier: 'Toxicroak' },
    { id: 458, identifier: 'Mantyke' },
    { id: 459, identifier: 'Snover' },
    { id: 460, identifier: 'Abomasnow' },
    { id: 461, identifier: 'Weavile' },
    { id: 464, identifier: 'Rhyperior' },
    { id: 468, identifier: 'Togekiss' },
    { id: 470, identifier: 'Leafeon' },
    { id: 471, identifier: 'Glaceon' },
    { id: 473, identifier: 'Mamoswine' },
    { id: 475, identifier: 'Gallade' },
    { id: 477, identifier: 'Dusknoir' },
    { id: 478, identifier: 'Froslass' },
    { id: 479, identifier: 'Rotom' },
    { id: 968, identifier: 'Rotom 1' },
    { id: 969, identifier: 'Rotom 2' },
    { id: 970, identifier: 'Rotom 3' },
    { id: 971, identifier: 'Rotom 4' },
    { id: 972, identifier: 'Rotom 5' },
    { id: 509, identifier: 'Purrloin' },
    { id: 510, identifier: 'Liepard' },
    { id: 517, identifier: 'Munna' },
    { id: 518, identifier: 'Musharna' },
    { id: 519, identifier: 'Pidove' },
    { id: 520, identifier: 'Tranquill' },
    { id: 521, identifier: 'Unfezant' },
    { id: 524, identifier: 'Roggenrola' },
    { id: 525, identifier: 'Boldore' },
    { id: 526, identifier: 'Gigalith' },
    { id: 527, identifier: 'Woobat' },
    { id: 528, identifier: 'Swoobat' },
    { id: 529, identifier: 'Drilbur' },
    { id: 530, identifier: 'Excadrill' },
    { id: 532, identifier: 'Timburr' },
    { id: 533, identifier: 'Gurdurr' },
    { id: 534, identifier: 'Conkeldurr' },
    { id: 535, identifier: 'Tympole' },
    { id: 536, identifier: 'Palpitoad' },
    { id: 537, identifier: 'Seismitoad' },
    { id: 538, identifier: 'Throh' },
    { id: 539, identifier: 'Sawk' },
    { id: 546, identifier: 'Cottonee' },
    { id: 547, identifier: 'Whimsicott' },
    { id: 550, identifier: 'Basculin' },
    { id: 992, identifier: 'Basculin 1' },
    { id: 554, identifier: 'Darumaka' },
    { id: 993, identifier: 'Darumaka 1' },
    { id: 555, identifier: 'Darmanitan' },
    { id: 994, identifier: 'Darmanitan 1' },
    { id: 995, identifier: 'Darmanitan 2' },
    { id: 996, identifier: 'Darmanitan 3' },
    { id: 556, identifier: 'Maractus' },
    { id: 557, identifier: 'Dwebble' },
    { id: 558, identifier: 'Crustle' },
    { id: 559, identifier: 'Scraggy' },
    { id: 560, identifier: 'Scrafty' },
    { id: 561, identifier: 'Sigilyph' },
    { id: 562, identifier: 'Yamask' },
    { id: 997, identifier: 'Yamask 1' },
    { id: 563, identifier: 'Cofagrigus' },
    { id: 568, identifier: 'Trubbish' },
    { id: 569, identifier: 'Garbodor' },
    { id: 572, identifier: 'Minccino' },
    { id: 573, identifier: 'Cinccino' },
    { id: 574, identifier: 'Gothita' },
    { id: 575, identifier: 'Gothorita' },
    { id: 576, identifier: 'Gothitelle' },
    { id: 577, identifier: 'Solosis' },
    { id: 578, identifier: 'Duosion' },
    { id: 579, identifier: 'Reuniclus' },
    { id: 582, identifier: 'Vanillite' },
    { id: 583, identifier: 'Vanillish' },
    { id: 584, identifier: 'Vanilluxe' },
    { id: 588, identifier: 'Karrablast' },
    { id: 589, identifier: 'Escavalier' },
    { id: 592, identifier: 'Frillish' },
    { id: 593, identifier: 'Jellicent' },
    { id: 595, identifier: 'Joltik' },
    { id: 596, identifier: 'Galvantula' },
    { id: 597, identifier: 'Ferroseed' },
    { id: 598, identifier: 'Ferrothorn' },
    { id: 599, identifier: 'Klink' },
    { id: 600, identifier: 'Klang' },
    { id: 601, identifier: 'Klinklang' },
    { id: 605, identifier: 'Elgyem' },
    { id: 606, identifier: 'Beheeyem' },
    { id: 607, identifier: 'Litwick' },
    { id: 608, identifier: 'Lampent' },
    { id: 609, identifier: 'Chandelure' },
    { id: 610, identifier: 'Axew' },
    { id: 611, identifier: 'Fraxure' },
    { id: 612, identifier: 'Haxorus' },
    { id: 613, identifier: 'Cubchoo' },
    { id: 614, identifier: 'Beartic' },
    { id: 616, identifier: 'Shelmet' },
    { id: 617, identifier: 'Accelgor' },
    { id: 618, identifier: 'Stunfisk' },
    { id: 100, identifier: 'Stunfisk 1' },
    { id: 622, identifier: 'Golett' },
    { id: 623, identifier: 'Golurk' },
    { id: 624, identifier: 'Pawniard' },
    { id: 625, identifier: 'Bisharp' },
    { id: 627, identifier: 'Rufflet' },
    { id: 628, identifier: 'Braviary' },
    { id: 629, identifier: 'Vullaby' },
    { id: 630, identifier: 'Mandibuzz' },
    { id: 631, identifier: 'Heatmor' },
    { id: 632, identifier: 'Durant' },
    { id: 633, identifier: 'Deino' },
    { id: 634, identifier: 'Zweilous' },
    { id: 635, identifier: 'Hydreigon' },
    { id: 638, identifier: 'Cobalion' },
    { id: 639, identifier: 'Terrakion' },
    { id: 640, identifier: 'Virizion' },
    { id: 643, identifier: 'Reshiram' },
    { id: 644, identifier: 'Zekrom' },
    { id: 646, identifier: 'Kyurem' },
    { id: 100, identifier: 'Kyurem 1' },
    { id: 100, identifier: 'Kyurem 2' },
    { id: 647, identifier: 'Keldeo' },
    { id: 101, identifier: 'Keldeo 1' },
    { id: 659, identifier: 'Bunnelby' },
    { id: 660, identifier: 'Diggersby' },
    { id: 674, identifier: 'Pancham' },
    { id: 675, identifier: 'Pangoro' },
    { id: 677, identifier: 'Espurr' },
    { id: 678, identifier: 'Meowstic' },
    { id: 109, identifier: 'Meowstic 1' },
    { id: 679, identifier: 'Honedge' },
    { id: 680, identifier: 'Doublade' },
    { id: 681, identifier: 'Aegislash' },
    { id: 109, identifier: 'Aegislash 1' },
    { id: 682, identifier: 'Spritzee' },
    { id: 683, identifier: 'Aromatisse' },
    { id: 684, identifier: 'Swirlix' },
    { id: 685, identifier: 'Slurpuff' },
    { id: 686, identifier: 'Inkay' },
    { id: 687, identifier: 'Malamar' },
    { id: 688, identifier: 'Binacle' },
    { id: 689, identifier: 'Barbaracle' },
    { id: 694, identifier: 'Helioptile' },
    { id: 695, identifier: 'Heliolisk' },
    { id: 700, identifier: 'Sylveon' },
    { id: 701, identifier: 'Hawlucha' },
    { id: 704, identifier: 'Goomy' },
    { id: 705, identifier: 'Sliggoo' },
    { id: 706, identifier: 'Goodra' },
    { id: 708, identifier: 'Phantump' },
    { id: 709, identifier: 'Trevenant' },
    { id: 710, identifier: 'Pumpkaboo' },
    { id: 109, identifier: 'Pumpkaboo 1' },
    { id: 110, identifier: 'Pumpkaboo 2' },
    { id: 110, identifier: 'Pumpkaboo 3' },
    { id: 711, identifier: 'Gourgeist' },
    { id: 110, identifier: 'Gourgeist 1' },
    { id: 110, identifier: 'Gourgeist 2' },
    { id: 110, identifier: 'Gourgeist 3' },
    { id: 712, identifier: 'Bergmite' },
    { id: 713, identifier: 'Avalugg' },
    { id: 714, identifier: 'Noibat' },
    { id: 715, identifier: 'Noivern' },
    { id: 722, identifier: 'Rowlet' },
    { id: 723, identifier: 'Dartrix' },
    { id: 724, identifier: 'Decidueye' },
    { id: 725, identifier: 'Litten' },
    { id: 726, identifier: 'Torracat' },
    { id: 727, identifier: 'Incineroar' },
    { id: 728, identifier: 'Popplio' },
    { id: 729, identifier: 'Brionne' },
    { id: 730, identifier: 'Primarina' },
    { id: 736, identifier: 'Grubbin' },
    { id: 737, identifier: 'Charjabug' },
    { id: 738, identifier: 'Vikavolt' },
    { id: 742, identifier: 'Cutiefly' },
    { id: 743, identifier: 'Ribombee' },
    { id: 746, identifier: 'Wishiwashi' },
    { id: 111, identifier: 'Wishiwashi 1' },
    { id: 747, identifier: 'Mareanie' },
    { id: 748, identifier: 'Toxapex' },
    { id: 749, identifier: 'Mudbray' },
    { id: 750, identifier: 'Mudsdale' },
    { id: 751, identifier: 'Dewpider' },
    { id: 752, identifier: 'Araquanid' },
    { id: 755, identifier: 'Morelull' },
    { id: 756, identifier: 'Shiinotic' },
    { id: 757, identifier: 'Salandit' },
    { id: 758, identifier: 'Salazzle' },
    { id: 759, identifier: 'Stufful' },
    { id: 760, identifier: 'Bewear' },
    { id: 761, identifier: 'Bounsweet' },
    { id: 762, identifier: 'Steenee' },
    { id: 763, identifier: 'Tsareena' },
    { id: 765, identifier: 'Oranguru' },
    { id: 766, identifier: 'Passimian' },
    { id: 767, identifier: 'Wimpod' },
    { id: 768, identifier: 'Golisopod' },
    { id: 771, identifier: 'Pyukumuku' },
    { id: 772, identifier: 'Type: Null' },
    { id: 773, identifier: 'Silvally' },
    { id: 111, identifier: 'Silvally 1' },
    { id: 111, identifier: 'Silvally 2' },
    { id: 112, identifier: 'Silvally 3' },
    { id: 112, identifier: 'Silvally 4' },
    { id: 112, identifier: 'Silvally 5' },
    { id: 112, identifier: 'Silvally 6' },
    { id: 112, identifier: 'Silvally 7' },
    { id: 112, identifier: 'Silvally 8' },
    { id: 112, identifier: 'Silvally 9' },
    { id: 112, identifier: 'Silvally 10' },
    { id: 112, identifier: 'Silvally 11' },
    { id: 112, identifier: 'Silvally 12' },
    { id: 113, identifier: 'Silvally 13' },
    { id: 113, identifier: 'Silvally 14' },
    { id: 113, identifier: 'Silvally 15' },
    { id: 113, identifier: 'Silvally 16' },
    { id: 113, identifier: 'Silvally 17' },
    { id: 776, identifier: 'Turtonator' },
    { id: 777, identifier: 'Togedemaru' },
    { id: 778, identifier: 'Mimikyu' },
    { id: 114, identifier: 'Mimikyu 1' },
    { id: 780, identifier: 'Drampa' },
    { id: 781, identifier: 'Dhelmise' },
    { id: 782, identifier: 'Jangmo-o' },
    { id: 783, identifier: 'Hakamo-o' },
    { id: 784, identifier: 'Kommo-o' },
    { id: 789, identifier: 'Cosmog' },
    { id: 790, identifier: 'Cosmoem' },
    { id: 791, identifier: 'Solgaleo' },
    { id: 792, identifier: 'Lunala' },
    { id: 800, identifier: 'Necrozma' },
    { id: 114, identifier: 'Necrozma 1' },
    { id: 115, identifier: 'Necrozma 2' },
    { id: 802, identifier: 'Marshadow' },
    { id: 807, identifier: 'Zeraora' },
    { id: 808, identifier: 'Meltan' },
    { id: 809, identifier: 'Melmetal' },
    { id: 810, identifier: 'Grookey' },
    { id: 811, identifier: 'Thwackey' },
    { id: 812, identifier: 'Rillaboom' },
    { id: 813, identifier: 'Scorbunny' },
    { id: 814, identifier: 'Raboot' },
    { id: 815, identifier: 'Cinderace' },
    { id: 816, identifier: 'Sobble' },
    { id: 817, identifier: 'Drizzile' },
    { id: 818, identifier: 'Inteleon' },
    { id: 819, identifier: 'Skwovet' },
    { id: 820, identifier: 'Greedent' },
    { id: 821, identifier: 'Rookidee' },
    { id: 822, identifier: 'Corvisquire' },
    { id: 823, identifier: 'Corviknight' },
    { id: 824, identifier: 'Blipbug' },
    { id: 825, identifier: 'Dottler' },
    { id: 826, identifier: 'Orbeetle' },
    { id: 827, identifier: 'Nickit' },
    { id: 828, identifier: 'Thievul' },
    { id: 829, identifier: 'Gossifleur' },
    { id: 830, identifier: 'Eldegoss' },
    { id: 831, identifier: 'Wooloo' },
    { id: 832, identifier: 'Dubwool' },
    { id: 833, identifier: 'Chewtle' },
    { id: 834, identifier: 'Drednaw' },
    { id: 835, identifier: 'Yamper' },
    { id: 836, identifier: 'Boltund' },
    { id: 837, identifier: 'Rolycoly' },
    { id: 838, identifier: 'Carkol' },
    { id: 839, identifier: 'Coalossal' },
    { id: 840, identifier: 'Applin' },
    { id: 841, identifier: 'Flapple' },
    { id: 842, identifier: 'Appletun' },
    { id: 843, identifier: 'Silicobra' },
    { id: 844, identifier: 'Sandaconda' },
    { id: 845, identifier: 'Cramorant' },
    { id: 115, identifier: 'Cramorant 1' },
    { id: 115, identifier: 'Cramorant 2' },
    { id: 846, identifier: 'Arrokuda' },
    { id: 847, identifier: 'Barraskewda' },
    { id: 848, identifier: 'Toxel' },
    { id: 849, identifier: 'Toxtricity' },
    { id: 115, identifier: 'Toxtricity 1' },
    { id: 850, identifier: 'Sizzlipede' },
    { id: 851, identifier: 'Centiskorch' },
    { id: 852, identifier: 'Clobbopus' },
    { id: 853, identifier: 'Grapploct' },
    { id: 854, identifier: 'Sinistea' },
    { id: 115, identifier: 'Sinistea 1' },
    { id: 855, identifier: 'Polteageist' },
    { id: 115, identifier: 'Polteageist 1' },
    { id: 856, identifier: 'Hatenna' },
    { id: 857, identifier: 'Hattrem' },
    { id: 858, identifier: 'Hatterene' },
    { id: 859, identifier: 'Impidimp' },
    { id: 860, identifier: 'Morgrem' },
    { id: 861, identifier: 'Grimmsnarl' },
    { id: 862, identifier: 'Obstagoon' },
    { id: 863, identifier: 'Perrserker' },
    { id: 864, identifier: 'Cursola' },
    { id: 865, identifier: 'Sirfetch’d' },
    { id: 866, identifier: 'Mr. Rime' },
    { id: 867, identifier: 'Runerigus' },
    { id: 868, identifier: 'Milcery' },
    { id: 869, identifier: 'Alcremie' },
    { id: 115, identifier: 'Alcremie 1' },
    { id: 115, identifier: 'Alcremie 2' },
    { id: 115, identifier: 'Alcremie 3' },
    { id: 116, identifier: 'Alcremie 4' },
    { id: 116, identifier: 'Alcremie 5' },
    { id: 116, identifier: 'Alcremie 6' },
    { id: 116, identifier: 'Alcremie 7' },
    { id: 116, identifier: 'Alcremie 8' },
    { id: 870, identifier: 'Falinks' },
    { id: 871, identifier: 'Pincurchin' },
    { id: 872, identifier: 'Snom' },
    { id: 873, identifier: 'Frosmoth' },
    { id: 874, identifier: 'Stonjourner' },
    { id: 875, identifier: 'Eiscue' },
    { id: 116, identifier: 'Eiscue 1' },
    { id: 876, identifier: 'Indeedee' },
    { id: 116, identifier: 'Indeedee 1' },
    { id: 877, identifier: 'Morpeko' },
    { id: 116, identifier: 'Morpeko 1' },
    { id: 878, identifier: 'Cufant' },
    { id: 879, identifier: 'Copperajah' },
    { id: 880, identifier: 'Dracozolt' },
    { id: 881, identifier: 'Arctozolt' },
    { id: 882, identifier: 'Dracovish' },
    { id: 883, identifier: 'Arctovish' },
    { id: 884, identifier: 'Duraludon' },
    { id: 885, identifier: 'Dreepy' },
    { id: 886, identifier: 'Drakloak' },
    { id: 887, identifier: 'Dragapult' },
    { id: 888, identifier: 'Zacian' },
    { id: 116, identifier: 'Zacian 1' },
    { id: 889, identifier: 'Zamazenta' },
    { id: 116, identifier: 'Zamazenta 1' },
    { id: 890, identifier: 'Eternatus' },
    { id: 117, identifier: 'Eternatus 1' },
]
